'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''HotelInvoiceDetailViewer class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class HotelInvoiceDetailViewer

    '''<summary>
    '''lblInvoiceIDCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceIDCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceNumberCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceNumberCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeriodCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatusCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrencyCodeCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrencyCodeCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrencyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrencyCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trMoneyExchange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMoneyExchange As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblMoneyExchangeCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMoneyExchangeCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMoneyExchange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMoneyExchange As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegistrationDateCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistrationDateCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegistrationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistrationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLimitToConciliateCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimitToConciliateCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLimitToConciliate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimitToConciliate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLimitToPayCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimitToPayCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLimitToPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLimitToPay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConciliationDateCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConciliationDateCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConciliationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConciliationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaymentDateCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymentDateCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaymentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymentDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReferenceBankCapion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferenceBankCapion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReferenceBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferenceBank As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHotelNameCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHotelNameCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHotelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHotelName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStreetAddressCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStreetAddressCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStreetAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPostalCodeCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostalCodeCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostalCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblZoneCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZoneCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocationCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trChargesExpander control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trChargesExpander As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''imgToggleCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgToggleCharges As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblChargesCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChargesCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCharges As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCharges As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''grdCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCharges As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''trCommissionsExpander control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCommissionsExpander As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''imgToggleCommissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgToggleCommissions As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCommissionsCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommissionsCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCommissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommissions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trCommissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCommissions As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''grdCommissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCommissions As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''trAmountCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAmountCharges As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblAmountChargesCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountChargesCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmountCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountCharges As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmountCommissionsCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountCommissionsCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmountCommissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountCommissions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubtotalCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubtotalCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubtotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTaxesCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTaxesCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTaxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTaxes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGrandTotalCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrandTotalCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGrandTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrandTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalanceCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalanceCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBalance As Global.System.Web.UI.WebControls.Label
End Class
