//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public int IdCiudad { get; set; }
        public int IdMunicipio { get; set; }
        public string Nombre { get; set; }
        public string codigo { get; set; }
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public Nullable<int> IdDiccionario { get; set; }
        public string keywords { get; set; }
        public Nullable<decimal> Distancia { get; set; }
        public Nullable<int> RatioSearch { get; set; }
    }
}
