//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporativos
    {
        public int idCorporativo { get; set; }
        public string NombreCorp { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string EmailContact { get; set; }
        public Nullable<bool> FacturacionGrupal { get; set; }
        public Nullable<bool> MostrarCatalogo { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
