//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporativos
    {
        public int idCorporativo { get; set; }
        public string NombreCorp { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string EmailContact { get; set; }
        public Nullable<bool> FacturacionGrupal { get; set; }
        public Nullable<bool> MostrarCatalogo { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
