//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diccionario
    {
        public int IdDiccionario { get; set; }
        public int IdIdioma { get; set; }
        public string Texto { get; set; }
        public int idRepl1 { get; set; }
    
        public virtual Indice Indice { get; set; }
    }
}
