//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elementos
    {
        public int IdElemento { get; set; }
        public string Nombre { get; set; }
        public int IdTipo { get; set; }
        public int IdModulo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> idGrupo { get; set; }
        public Nullable<byte> GrupoTipo { get; set; }
        public Nullable<byte> GrupoMax { get; set; }
    }
}
