//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoteles()
        {
            this.RatesPlan = new HashSet<RatesPlan>();
        }
    
        public int idHotel { get; set; }
        public int idEmpresa { get; set; }
        public byte Categoria { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public int idMoneda { get; set; }
        public byte MaxDiasRenta { get; set; }
        public byte MaxNumCuartos { get; set; }
        public byte MaxNumAdultos { get; set; }
        public byte MaxNumNinios { get; set; }
        public byte DiasLibres { get; set; }
        public Nullable<byte> DiasMinCancelar { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public byte EdadApartirPagaExtra { get; set; }
        public byte MaxEdadNinio { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public Nullable<int> idfranquicia { get; set; }
        public string CiudadCercana { get; set; }
        public string AeropuertoCercano { get; set; }
        public Nullable<decimal> CityTax { get; set; }
        public Nullable<decimal> OccupancyTax { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<decimal> ComisionAgentes { get; set; }
        public string PoliticaCancelacion { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaInicioRes { get; set; }
        public string EmailReservas { get; set; }
        public string PropertyNumber { get; set; }
        public Nullable<bool> GetRates { get; set; }
        public string ChainCode { get; set; }
        public string DepartureRestricted { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string NotApplyRestrictedDays { get; set; }
        public Nullable<decimal> HurdleRate { get; set; }
        public Nullable<short> CancelPrioridad { get; set; }
        public Nullable<short> MinLengthStay { get; set; }
        public string StatusAvailability { get; set; }
        public Nullable<decimal> defaultComission { get; set; }
        public Nullable<decimal> defaultComissionVal { get; set; }
        public string PGalileo { get; set; }
        public string PAmadeus { get; set; }
        public string PSabre { get; set; }
        public string PWorldspan { get; set; }
        public Nullable<bool> PlusTax { get; set; }
        public string PoliticaGarantia { get; set; }
        public string PoliticaCreditCard { get; set; }
        public string ExtraCargos { get; set; }
        public string idiomaemail { get; set; }
        public string noarrivals { get; set; }
        public Nullable<byte> CancelPriorHours { get; set; }
        public string CancelPriorSpecificT { get; set; }
        public Nullable<int> UserPerfil { get; set; }
        public Nullable<bool> SendFaxReserva { get; set; }
        public string emailComments { get; set; }
        public Nullable<int> idDiccemailComments { get; set; }
        public string urlWebSite { get; set; }
        public Nullable<int> idDiccUrlWebSite { get; set; }
        public Nullable<bool> AvailOnPortal { get; set; }
        public Nullable<bool> AvailOnGDS { get; set; }
        public Nullable<bool> AvailOnOnePage { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<bool> AllowBankDeposit { get; set; }
        public Nullable<bool> Emprhotur { get; set; }
        public Nullable<bool> AmhmRes { get; set; }
        public Nullable<int> idCorporativo { get; set; }
        public Nullable<int> idDiccExtraCargos { get; set; }
        public Nullable<int> idDiccPoliticaGarantia { get; set; }
        public Nullable<int> idDiccPoliticaCreditCard { get; set; }
        public Nullable<int> idDiccPoliticaCancelacionFull { get; set; }
        public Nullable<int> idDiccPoliticaCancelacionReview { get; set; }
        public Nullable<bool> AvailOnADS { get; set; }
        public Nullable<bool> EsMoroso { get; set; }
        public Nullable<bool> EsPagoCero { get; set; }
        public Nullable<bool> AvailOnIDS { get; set; }
        public Nullable<byte> MinNumCuartos { get; set; }
        public Nullable<byte> MinEdadNinio { get; set; }
        public Nullable<byte> MaxNumOcupacion { get; set; }
        public Nullable<byte> MinNumOcupacion { get; set; }
        public Nullable<bool> AllowSpecificPayment { get; set; }
        public Nullable<bool> AllowBankDepositCCT { get; set; }
        public Nullable<bool> TransbyEmail { get; set; }
        public Nullable<byte> maxEdadAdolecente { get; set; }
        public Nullable<byte> EdadAdolecente { get; set; }
        public Nullable<bool> AvlOnCorpModule { get; set; }
        public Nullable<int> idcadena { get; set; }
        public Nullable<short> FechaConstruccion { get; set; }
        public Nullable<System.DateTime> FechaFundacion { get; set; }
        public Nullable<short> FechaRemodelacion { get; set; }
        public Nullable<short> ConfirmacionTelefonica { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> ISH { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<bool> SaveCurrencyShown { get; set; }
        public Nullable<bool> IsHouse { get; set; }
        public Nullable<int> tipoPago { get; set; }
        public Nullable<int> IdOwnerDesc { get; set; }
        public Nullable<bool> AmaLlaves { get; set; }
        public Nullable<int> CategoriaCasa { get; set; }
        public Nullable<decimal> Banios { get; set; }
        public Nullable<int> Area { get; set; }
        public string AreaUnidad { get; set; }
        public string ApiKey { get; set; }
        public Nullable<bool> isSingleImgInv { get; set; }
        public Nullable<bool> IsPMSPushNotifActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatesPlan> RatesPlan { get; set; }
    }
}
