//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockRoomTypes
    {
        public Nullable<int> idhotel { get; set; }
        public string IdRatePlan { get; set; }
        public Nullable<int> idTipoHabitacion_Hotel { get; set; }
        public string StatusAvail { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int idRepl4 { get; set; }
    }
}
