//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OzHotelesEntities : DbContext
    {
        public OzHotelesEntities()
            : base("name=OzHotelesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RatesPlan> RatesPlan { get; set; }
        public virtual DbSet<Tarifas> Tarifas { get; set; }
        public virtual DbSet<TarifasRestricciones> TarifasRestricciones { get; set; }
        public virtual DbSet<Diccionario> Diccionario { get; set; }
        public virtual DbSet<Indice> Indice { get; set; }
        public virtual DbSet<vReservation> vReservation { get; set; }
        public virtual DbSet<vRoomInventory> vRoomInventory { get; set; }
        public virtual DbSet<ContratosNR> ContratosNR { get; set; }
        public virtual DbSet<vHotelByUser> vHotelByUser { get; set; }
        public virtual DbSet<vAdministrator> vAdministrator { get; set; }
        public virtual DbSet<vHotelPlan> vHotelPlan { get; set; }
        public virtual DbSet<vHotelBasicInfo> vHotelBasicInfo { get; set; }
        public virtual DbSet<vDayRateDetail> vDayRateDetail { get; set; }
        public virtual DbSet<vDayRates> vDayRates { get; set; }
        public virtual DbSet<vHotelRoom> vHotelRoom { get; set; }
    }
}
