//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OzHotelesEntities : DbContext
    {
        public OzHotelesEntities()
            : base("name=OzHotelesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RatesPlan> RatesPlan { get; set; }
        public virtual DbSet<Tarifas> Tarifas { get; set; }
        public virtual DbSet<TarifasRestricciones> TarifasRestricciones { get; set; }
        public virtual DbSet<Diccionario> Diccionario { get; set; }
        public virtual DbSet<Indice> Indice { get; set; }
        public virtual DbSet<vRoomInventory> vRoomInventory { get; set; }
        public virtual DbSet<ContratosNR> ContratosNR { get; set; }
        public virtual DbSet<vHotelByUser> vHotelByUser { get; set; }
        public virtual DbSet<vAdministrator> vAdministrator { get; set; }
        public virtual DbSet<vHotelPlan> vHotelPlan { get; set; }
        public virtual DbSet<vHotelBasicInfo> vHotelBasicInfo { get; set; }
        public virtual DbSet<vDayRateDetail> vDayRateDetail { get; set; }
        public virtual DbSet<vHotelRoom> vHotelRoom { get; set; }
        public virtual DbSet<vDayRates> vDayRates { get; set; }
        public virtual DbSet<vPermissions> vPermissions { get; set; }
        public virtual DbSet<VReservationRoomPriceDetails> VReservationRoomPriceDetails { get; set; }
        public virtual DbSet<Hoteles> Hoteles { get; set; }
        public virtual DbSet<Corporativos> Corporativos { get; set; }
        public virtual DbSet<TarjetasHotel> TarjetasHotel { get; set; }
        public virtual DbSet<PrepagoRatesPlan> PrepagoRatesPlan { get; set; }
        public virtual DbSet<vReservationPayments> vReservationPayments { get; set; }
        public virtual DbSet<vReservation> vReservation { get; set; }
        public virtual DbSet<vReservationDetails> vReservationDetails { get; set; }
        public virtual DbSet<vReservationRoomDetails> vReservationRoomDetails { get; set; }
        public virtual DbSet<vPromotions> vPromotions { get; set; }
    
        public virtual int spReservationCancel(Nullable<int> idReservacion, string noConfCancelGalileo, string noCancelacion, string txCode, Nullable<bool> statusConf, string systemCode, string travelAgencyName, string voucher, string wizcomPassOn, string wizcomSequenceNumber, string motivoCancelacion, Nullable<bool> cancelWithError, string sessionId, Nullable<int> iduser)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var noConfCancelGalileoParameter = noConfCancelGalileo != null ?
                new ObjectParameter("NoConfCancelGalileo", noConfCancelGalileo) :
                new ObjectParameter("NoConfCancelGalileo", typeof(string));
    
            var noCancelacionParameter = noCancelacion != null ?
                new ObjectParameter("NoCancelacion", noCancelacion) :
                new ObjectParameter("NoCancelacion", typeof(string));
    
            var txCodeParameter = txCode != null ?
                new ObjectParameter("TxCode", txCode) :
                new ObjectParameter("TxCode", typeof(string));
    
            var statusConfParameter = statusConf.HasValue ?
                new ObjectParameter("StatusConf", statusConf) :
                new ObjectParameter("StatusConf", typeof(bool));
    
            var systemCodeParameter = systemCode != null ?
                new ObjectParameter("SystemCode", systemCode) :
                new ObjectParameter("SystemCode", typeof(string));
    
            var travelAgencyNameParameter = travelAgencyName != null ?
                new ObjectParameter("TravelAgencyName", travelAgencyName) :
                new ObjectParameter("TravelAgencyName", typeof(string));
    
            var voucherParameter = voucher != null ?
                new ObjectParameter("Voucher", voucher) :
                new ObjectParameter("Voucher", typeof(string));
    
            var wizcomPassOnParameter = wizcomPassOn != null ?
                new ObjectParameter("WizcomPassOn", wizcomPassOn) :
                new ObjectParameter("WizcomPassOn", typeof(string));
    
            var wizcomSequenceNumberParameter = wizcomSequenceNumber != null ?
                new ObjectParameter("WizcomSequenceNumber", wizcomSequenceNumber) :
                new ObjectParameter("WizcomSequenceNumber", typeof(string));
    
            var motivoCancelacionParameter = motivoCancelacion != null ?
                new ObjectParameter("MotivoCancelacion", motivoCancelacion) :
                new ObjectParameter("MotivoCancelacion", typeof(string));
    
            var cancelWithErrorParameter = cancelWithError.HasValue ?
                new ObjectParameter("CancelWithError", cancelWithError) :
                new ObjectParameter("CancelWithError", typeof(bool));
    
            var sessionIdParameter = sessionId != null ?
                new ObjectParameter("SessionId", sessionId) :
                new ObjectParameter("SessionId", typeof(string));
    
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spReservationCancel", idReservacionParameter, noConfCancelGalileoParameter, noCancelacionParameter, txCodeParameter, statusConfParameter, systemCodeParameter, travelAgencyNameParameter, voucherParameter, wizcomPassOnParameter, wizcomSequenceNumberParameter, motivoCancelacionParameter, cancelWithErrorParameter, sessionIdParameter, iduserParameter);
        }
    
        public virtual int spModificarReservacionByid(Nullable<int> idReservacion, string nombreCL, string apellidoCL, Nullable<decimal> total, Nullable<decimal> totalNR, Nullable<System.DateTime> checkIn, Nullable<System.DateTime> checkOut)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var nombreCLParameter = nombreCL != null ?
                new ObjectParameter("NombreCL", nombreCL) :
                new ObjectParameter("NombreCL", typeof(string));
    
            var apellidoCLParameter = apellidoCL != null ?
                new ObjectParameter("ApellidoCL", apellidoCL) :
                new ObjectParameter("ApellidoCL", typeof(string));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(decimal));
    
            var totalNRParameter = totalNR.HasValue ?
                new ObjectParameter("TotalNR", totalNR) :
                new ObjectParameter("TotalNR", typeof(decimal));
    
            var checkInParameter = checkIn.HasValue ?
                new ObjectParameter("CheckIn", checkIn) :
                new ObjectParameter("CheckIn", typeof(System.DateTime));
    
            var checkOutParameter = checkOut.HasValue ?
                new ObjectParameter("CheckOut", checkOut) :
                new ObjectParameter("CheckOut", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarReservacionByid", idReservacionParameter, nombreCLParameter, apellidoCLParameter, totalParameter, totalNRParameter, checkInParameter, checkOutParameter);
        }
    
        public virtual ObjectResult<GetMappedHotelsWithRatePlan_Result> GetMappedHotelsWithRatePlan(Nullable<int> corporateId, string ratePlanF2G, string promoCode)
        {
            var corporateIdParameter = corporateId.HasValue ?
                new ObjectParameter("corporateId", corporateId) :
                new ObjectParameter("corporateId", typeof(int));
    
            var ratePlanF2GParameter = ratePlanF2G != null ?
                new ObjectParameter("ratePlanF2G", ratePlanF2G) :
                new ObjectParameter("ratePlanF2G", typeof(string));
    
            var promoCodeParameter = promoCode != null ?
                new ObjectParameter("promoCode", promoCode) :
                new ObjectParameter("promoCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMappedHotelsWithRatePlan_Result>("GetMappedHotelsWithRatePlan", corporateIdParameter, ratePlanF2GParameter, promoCodeParameter);
        }
    
        public virtual ObjectResult<GetAllF2GCode_Result> GetAllF2GCode(Nullable<int> corporateId)
        {
            var corporateIdParameter = corporateId.HasValue ?
                new ObjectParameter("corporateId", corporateId) :
                new ObjectParameter("corporateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllF2GCode_Result>("GetAllF2GCode", corporateIdParameter);
        }
    
        public virtual int UpdateF2GRatePlan(string idRatePlanUv, Nullable<int> idHotel, string idRatePlanF2G, string promoCode, Nullable<int> action)
        {
            var idRatePlanUvParameter = idRatePlanUv != null ?
                new ObjectParameter("idRatePlanUv", idRatePlanUv) :
                new ObjectParameter("idRatePlanUv", typeof(string));
    
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var idRatePlanF2GParameter = idRatePlanF2G != null ?
                new ObjectParameter("idRatePlanF2G", idRatePlanF2G) :
                new ObjectParameter("idRatePlanF2G", typeof(string));
    
            var promoCodeParameter = promoCode != null ?
                new ObjectParameter("promoCode", promoCode) :
                new ObjectParameter("promoCode", typeof(string));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateF2GRatePlan", idRatePlanUvParameter, idHotelParameter, idRatePlanF2GParameter, promoCodeParameter, actionParameter);
        }
    }
}
