//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OzUniEntities : DbContext
    {
        public OzUniEntities()
            : base("name=OzUniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Portales> Portales { get; set; }
        public virtual DbSet<AplicacionPortal> AplicacionPortal { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<Elementos> Elementos { get; set; }
    
        public virtual ObjectResult<GetHotelsByCorporateId_Result> GetHotelsByCorporateId(Nullable<int> corporateId)
        {
            var corporateIdParameter = corporateId.HasValue ?
                new ObjectParameter("corporateId", corporateId) :
                new ObjectParameter("corporateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelsByCorporateId_Result>("GetHotelsByCorporateId", corporateIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spCreateUserConfigurationConectivity(Nullable<int> companyId, Nullable<int> hotelId, string userName, string password, Nullable<bool> addToHotelPms)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("hotelId", hotelId) :
                new ObjectParameter("hotelId", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var addToHotelPmsParameter = addToHotelPms.HasValue ?
                new ObjectParameter("addToHotelPms", addToHotelPms) :
                new ObjectParameter("addToHotelPms", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCreateUserConfigurationConectivity", companyIdParameter, hotelIdParameter, userNameParameter, passwordParameter, addToHotelPmsParameter);
        }
    }
}
