//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OzUniEntities : DbContext
    {
        public OzUniEntities()
            : base("name=OzUniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Portales> Portales { get; set; }
        public virtual DbSet<AplicacionPortal> AplicacionPortal { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
    
        public virtual ObjectResult<GetHotelsByCorporateId_Result> GetHotelsByCorporateId(Nullable<int> corporateId)
        {
            var corporateIdParameter = corporateId.HasValue ?
                new ObjectParameter("corporateId", corporateId) :
                new ObjectParameter("corporateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelsByCorporateId_Result>("GetHotelsByCorporateId", corporateIdParameter);
        }
    }
}
