//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepagoRatesPlan
    {
        public int IdPrepagoRatesPlan { get; set; }
        public string RateCode { get; set; }
        public int IdHotel { get; set; }
        public string Source { get; set; }
        public Nullable<short> PrepagoTipo { get; set; }
        public Nullable<decimal> PrepaymentPerc { get; set; }
    }
}
