//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatesPlan
    {
        public string idRatePlan { get; set; }
        public string Description { get; set; }
        public int IdHotel { get; set; }
        public string Segment { get; set; }
        public Nullable<int> IdDictionaryDescription { get; set; }
        public string AccessCode { get; set; }
        public string CorporateDisscount { get; set; }
        public Nullable<int> IdHotelPlan { get; set; }
        public Nullable<bool> SegmentRacPrinc { get; set; }
        public Nullable<int> idRule { get; set; }
        public string Name { get; set; }
        public Nullable<bool> RateCCT { get; set; }
        public Nullable<int> QtyRooms { get; set; }
        public Nullable<bool> RateGDS { get; set; }
        public Nullable<bool> RatePortal { get; set; }
        public Nullable<bool> RateUnip { get; set; }
        public Nullable<int> IdDiccShortDesc { get; set; }
        public string codigotarifa { get; set; }
        public Nullable<decimal> DescPromotion { get; set; }
        public Nullable<short> DaysFree { get; set; }
        public Nullable<short> DepositType { get; set; }
        public Nullable<bool> RateADS { get; set; }
        public string gdsApply { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<decimal> ComGDS { get; set; }
        public Nullable<decimal> ComPortal { get; set; }
        public Nullable<decimal> ComOnePage { get; set; }
        public Nullable<decimal> ComADS { get; set; }
        public Nullable<int> idContrado { get; set; }
        public Nullable<int> idContrato { get; set; }
        public Nullable<bool> RateIDS { get; set; }
        public Nullable<int> idMoneda { get; set; }
        public Nullable<bool> WaitListAvailable { get; set; }
        public Nullable<int> idDiccPromoDesc { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> RatePlanRac { get; set; }
        public Nullable<bool> hotelPayment { get; set; }
        public Nullable<int> tipoPago { get; set; }
        public Nullable<bool> IsPromo { get; set; }
        public Nullable<short> TipoDescuento { get; set; }
        public Nullable<bool> DaysFreeType { get; set; }
        public Nullable<int> DiscountLevel { get; set; }
        public Nullable<bool> IsCombinablePromotion { get; set; }
        public Nullable<bool> IsMobileRate { get; set; }
        public Nullable<bool> IsCallCenterOnly { get; set; }
        public Nullable<bool> DeletedInGoogle { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
        public virtual RatesPlanRules RatesPlanRules { get; set; }
    }
}
