//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatesPlanRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RatesPlanRules()
        {
            this.RatesPlan = new HashSet<RatesPlan>();
        }
    
        public int idRule { get; set; }
        public int IdHotel { get; set; }
        public Nullable<bool> ReqVerification { get; set; }
        public string GuarDep { get; set; }
        public Nullable<bool> RateRulesDefault { get; set; }
        public Nullable<byte> DepositNights { get; set; }
        public Nullable<byte> DepositPerc { get; set; }
        public Nullable<byte> CancelPriorHours { get; set; }
        public Nullable<byte> CancelPriorDays { get; set; }
        public string RuleDescription { get; set; }
        public Nullable<byte> AdvBooking { get; set; }
        public Nullable<byte> MaxDias { get; set; }
        public Nullable<byte> MinDias { get; set; }
        public string NoArrivos { get; set; }
        public string CancelPriorSpecificT { get; set; }
        public string PoliticaCancelacion { get; set; }
        public Nullable<int> idDiccionarioPoliticaCancelacionReview { get; set; }
        public Nullable<int> idDiccionarioPoliticaCancelacionFull { get; set; }
        public string PoliticaGarantia { get; set; }
        public Nullable<int> idDiccPoliticaGarantia { get; set; }
        public string PoliticaCreditCard { get; set; }
        public Nullable<int> idDiccPoliticaCreditCard { get; set; }
        public Nullable<int> MaxAdvBooking { get; set; }
        public Nullable<System.DateTime> PromoStartDate { get; set; }
        public Nullable<System.DateTime> PromoEndDate { get; set; }
        public string PromoSpecificDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatesPlan> RatesPlan { get; set; }
    }
}
