//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationsDeposits
    {
        public int idreservacion { get; set; }
        public string nocuenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string banco { get; set; }
        public string referencia { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> dep_monto { get; set; }
        public string dep_moneda { get; set; }
        public string moneda { get; set; }
        public string DepositTarget { get; set; }
        public Nullable<int> IdDiccDepositInfo { get; set; }
    
        public virtual Reservaciones Reservaciones { get; set; }
    }
}
