//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomInventory
    {
        public System.DateTime Date { get; set; }
        public int RoomId { get; set; }
        public byte Status { get; set; }
        public short FullInventory { get; set; }
        public Nullable<int> Reserved { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
