//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifasRestricciones
    {
        public int idRestriccion { get; set; }
        public int idTarifa { get; set; }
        public decimal TarifaAdulto { get; set; }
        public decimal TarifaNinio { get; set; }
        public int Adultos { get; set; }
        public int Ninios { get; set; }
        public Nullable<decimal> TarifaAdultoExc { get; set; }
        public Nullable<decimal> TarifaNinioExc { get; set; }
        public Nullable<decimal> TarifaAdultoNR { get; set; }
        public Nullable<decimal> TarifaNinioNR { get; set; }
        public Nullable<decimal> TarifaAdultoExcNR { get; set; }
        public Nullable<decimal> TarifaNinioExcNR { get; set; }
        public Nullable<decimal> TarifaAdolescente { get; set; }
        public Nullable<decimal> TarifaAdolescenteExc { get; set; }
        public Nullable<decimal> TarifaAdolescenteNR { get; set; }
        public Nullable<decimal> TarifaAdolescenteExcNR { get; set; }
        public string Applyday { get; set; }
    
        public virtual Tarifas Tarifas { get; set; }
    }
}
