//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDayRates
    {
        public int RateId { get; set; }
        public int HotelId { get; set; }
        public int RoomId { get; set; }
        public string RatePlanId { get; set; }
        public string RatePlanName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string NoArrivalsMap { get; set; }
        public string ExceptionMap { get; set; }
        public byte Occupancy { get; set; }
        public decimal Price { get; set; }
        public decimal ExceptionPrice { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> Offset { get; set; }
        public string Currency { get; set; }
        public string ParentRatePlanId { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<long> Id { get; set; }
        public decimal DayDiscount { get; set; }
        public int DiscountLevel { get; set; }
    }
}
