//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHotelRoom
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int HotelId { get; set; }
        public int TotalRooms { get; set; }
        public byte MaxOccupancy { get; set; }
        public byte ExtraOccupancyAllowed { get; set; }
        public byte MaxAdultsOccupancy { get; set; }
        public byte MinAdultsOccupancy { get; set; }
        public byte MaxChildrenOccupancy { get; set; }
        public Nullable<bool> JuniorsAllowed { get; set; }
        public short Order { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<int> ParentRoomId { get; set; }
        public string ParenteRoomCode { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> Offset { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Language { get; set; }
    }
}
