//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHotelPlan
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int HotelId { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Language { get; set; }
        public int CommissionPercentage { get; set; }
        public string Segment { get; set; }
        public Nullable<bool> IsLinked { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsPromo { get; set; }
        public Nullable<int> ContractId { get; set; }
    }
}
