//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPromotions
    {
        public string idRatePlan { get; set; }
        public int IdHotel { get; set; }
        public Nullable<decimal> DescPromotion { get; set; }
        public Nullable<short> DaysFree { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<short> TipoDescuento { get; set; }
        public Nullable<bool> DaysFreeType { get; set; }
        public Nullable<int> DiscountLevel { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public Nullable<byte> CancelPriorHours { get; set; }
        public Nullable<byte> CancelPriorDays { get; set; }
        public string RuleDescription { get; set; }
        public Nullable<byte> AdvBooking { get; set; }
        public Nullable<byte> MaxDias { get; set; }
        public Nullable<byte> MinDias { get; set; }
        public string NoArrivos { get; set; }
        public string CancelPriorSpecificT { get; set; }
        public string PoliticaCancelacion { get; set; }
        public Nullable<int> idDiccionarioPoliticaCancelacionReview { get; set; }
        public Nullable<int> idDiccionarioPoliticaCancelacionFull { get; set; }
        public Nullable<int> MaxAdvBooking { get; set; }
        public Nullable<System.DateTime> PromoStartDate { get; set; }
        public Nullable<System.DateTime> PromoEndDate { get; set; }
        public string PromoSpecificDays { get; set; }
        public Nullable<int> IdDictionaryDescription { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdDiccShortDesc { get; set; }
    }
}
