//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReservationDetails
    {
        public Nullable<int> hotelId { get; set; }
        public string hotelName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public byte status { get; set; }
        public string accessCode { get; set; }
        public System.DateTime reservationDate { get; set; }
        public System.DateTime checkIn { get; set; }
        public System.DateTime checkOut { get; set; }
        public string source { get; set; }
        public string Portal { get; set; }
        public string Provisioner { get; set; }
        public int reservationId { get; set; }
        public string reservationNumber { get; set; }
        public string cancellationNumber { get; set; }
        public string cancellationReason { get; set; }
        public string reservationIdXProvider { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> totalNetRate { get; set; }
        public Nullable<bool> includesTax { get; set; }
        public decimal tax { get; set; }
        public decimal ecotasa { get; set; }
        public string currency { get; set; }
        public string ratePlan { get; set; }
        public bool IsNetRateUV { get; set; }
        public string customerName { get; set; }
        public string customerLastName { get; set; }
        public string customerEmail { get; set; }
        public string customerPhone { get; set; }
        public Nullable<int> paymentType { get; set; }
        public string onlinePaymentMethod { get; set; }
        public string authorizationNumber { get; set; }
        public string cardNumber { get; set; }
        public string cardExpMonth { get; set; }
        public string cardExpYear { get; set; }
        public string cardCvv { get; set; }
        public string cardCustomerName { get; set; }
        public decimal amountTotal { get; set; }
        public decimal depositAmount { get; set; }
        public string depositCurrency { get; set; }
        public string depositReference { get; set; }
        public string depositTarget { get; set; }
        public int provider { get; set; }
        public string rp_cancellationPolicies { get; set; }
        public string rp_guaranteePolicies { get; set; }
        public string rp_creditcardPolicies { get; set; }
        public string h_cancellationPolicies { get; set; }
        public string h_guaranteePolicies { get; set; }
        public string h_creditcardPolicies { get; set; }
        public string pmsReservationNumber { get; set; }
        public Nullable<bool> pmsStatus { get; set; }
        public string pmsAction { get; set; }
        public Nullable<int> pmsFailedAttempts { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<int> agencyId { get; set; }
        public string agency { get; set; }
        public string agencyUser { get; set; }
        public Nullable<int> corporateId { get; set; }
        public string corporateName { get; set; }
        public string hotelEmail { get; set; }
        public string modificationReason { get; set; }
        public string ratePlanPromotion { get; set; }
        public string namePromotion { get; set; }
        public Nullable<int> idCancellationUser { get; set; }
        public string userCancellation { get; set; }
        public string depositBank { get; set; }
        public string reservationIdIDS { get; set; }
        public string paymentInformation { get; set; }
    }
}
