//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReservationRoomDetails
    {
        public Nullable<int> roomTypeId { get; set; }
        public int reservationId { get; set; }
        public int roomPriceId { get; set; }
        public string roomName { get; set; }
        public string roomCode { get; set; }
        public string roomDescription { get; set; }
        public string roomPreferences { get; set; }
        public byte adults { get; set; }
        public Nullable<byte> extraAdults { get; set; }
        public byte childrens { get; set; }
        public Nullable<byte> extraChildrens { get; set; }
        public string ageChildren { get; set; }
        public Nullable<System.DateTime> roomCheckIn { get; set; }
        public Nullable<System.DateTime> roomCheckOut { get; set; }
        public string ratePlan { get; set; }
        public string rateCode { get; set; }
        public string currency { get; set; }
    }
}
