//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReservationDetails
    {
        public string hotelName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public byte status { get; set; }
        public string accessCode { get; set; }
        public System.DateTime reservationDate { get; set; }
        public System.DateTime checkIn { get; set; }
        public System.DateTime checkOut { get; set; }
        public string source { get; set; }
        public int reservationId { get; set; }
        public string reservationIdXProvider { get; set; }
        public decimal totalReservation { get; set; }
        public string TotalProviderCurrencyCode { get; set; }
        public string customerName { get; set; }
        public string customerEmail { get; set; }
        public string customerPhone { get; set; }
        public string paymentMethod { get; set; }
        public string onlinePaymentMethod { get; set; }
        public string authorizationNumber { get; set; }
        public string cardNumber { get; set; }
        public string cardExpMonth { get; set; }
        public string cardExpYear { get; set; }
        public string cardCvv { get; set; }
        public string cardCustomerName { get; set; }
        public int provider { get; set; }
    }
}
