//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRoomInventory
    {
        public System.DateTime Date { get; set; }
        public int RoomId { get; set; }
        public int HotelId { get; set; }
        public short FullInventory { get; set; }
        public Nullable<int> Reserved { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
