export default {
    'Synchronize Rates in Channel Manager' : 'Sincronizar Tarifas en Channel  Manager',
    'Rates Updated' : 'Tarifas Actualizadas',
    'System Error' : 'Error de Sistema',
    'Exit' : 'Salir',
    'Update Rates' : 'Sincronizar Tarifas',
    'Update Closures' : 'Sincronizar Cierres',
    'This operation make take a few minutes' : 'Esta operación puede tomar unos minutos',
    'Updated' : 'Actualizado',
    'Fail' : 'No Actualizado',
    'One or more requests were not successful. Check logs.' : 'Uno o más peticiones no se realizaron correctamente. Verificar registros.',
    'Restrictions' : 'Restricciones',
    'Closures' : 'Cierres',
    'Restriction RatePlan' : 'Cierres por Plan Tarifario',
    'Restriction General' : 'Cierre General',
    'Restriction Promos' : 'Cierre General Promociones',
    'Restriction by Room and RatePlan' : 'Cierre por Habitación y Plan Tarifario',
    'Synchronize with Google Hotel Center' : 'Sincronizar con Google Hotel Center',
    'Prices' : 'Precios',
    'Closure' : 'Cierres',
    'This action will only send the closings to Google Hotel Center from the selected dates' : 'Esta acción sólo enviará los cierres a Google Hotel Center a partir de las fechas seleccionadas',
    'This action will only send the prices to Google Hotel Center from the selected dates' : 'Esta acción solo enviara los precios a google hotel center a partir de las fechas seleccionadas',
    'Enable Google Prices in Content / General Information' : 'Habilitar Precios Google en Contenido / Información General',
    'Show Availability' : 'Mostrar Disponibilidad',
    'Date Range' : 'Rango de Fechas',
    'Inventory' : 'Inventario',
    'Rate Plans' : 'Planes Tarifarios',
    'Rooms' : 'Habitaciones',
    'All' : 'Todos',
    'Su' : 'Do',
    'Mo' : 'Lu',
    'Tu' : 'Ma',
    'We' : 'Mi',
    'Th' : 'Ju',
    'Fr' : 'Vi',
    'Sa' : 'Sa',
    'Update Inventory' : 'Sincronizar Inventario',
    'Inventory Updated' : 'Inventario Actualizado',
    'Days of the Week' : 'Días de la Semana',
    'This action will only send the inventory to Google Hotel Center from the selected dates' : 'Esta acción sólo enviará el inventario a Google Hotel Center a partir de la fechas seleccionadas',
    'The listings only show the base plans and rooms, when sending the rates of these, the linked ones will also be sent':'En los listados solo se muestran los planes y habitaciones base, al enviar las tarifas de estos se enviaran también las vinculadas',
    'Delete Rates' : 'Eliminar Tarifas',
    'Promotions' : 'Promociones',
    'Include Rates Promotions' : 'Incluir Tarifas Promociones',
    'Include Rates Of RatePlans' : 'Incluir Tarifas de Planes Tarifarios',
    'Rates Eliminated' : 'Tarifas Eliminadas',
    'Choose Dates' : 'Elegir Fechas',
    'Enable Google Prices Or Rates APICache in Content / General Information' : 'Habilitar Precios Google ó Tarifas APICache en Contenido / Información General'

}