export default {
    'Customer information': 'Información del cliente',
    Name: 'Nombre',
    'Last names': 'Apellidos',
    Phone: 'Teléfono',
    Email: 'Correo electrónico',
    'Card number': 'Número de tarjeta',
    Show: 'Mostrar',
    Type: 'Tipo',
    'Security code': 'Código de seguridad',
    'Expiration date': 'Fecha de expiración',
    Hide: 'Ocultar',
    'Check in': 'Llegada',
    'Check out': 'Salida',
    'Check In' : 'Fecha de Llegada',
    'Check Out': 'Fecha de Salida',
    'Reservation date': 'Fecha de reservación',
    'Client data': 'Datos del cliente',
    'Your reservation was modified': 'Su reserva fue modificada',
    'Your reservation was canceled': 'Su reserva fue cancelada',
    'Your reservation was reactivated': 'Su reserva fue reactivada',
    'Failed to modify the reservation': 'Error al modificar la reserva',
    'Failed to cancel the reservation': 'Error al cancelar la reserva',
    'Failed to reactivate the reservation': 'Error al reactivar la reserva',
    'Modify reservation': 'Modificar reserva',
    Modify: 'Modificar',
    Cancel: 'Cancelar',
    'Are you sure you want to cancel?': '¿Seguro que desea cancelar?',
    'Reason to cancel': 'Motivo para cancelar',
    Exit: 'Salir',
    'Reservation details': 'Detalles de la reservación',
    Policies: 'Políticas',
    'Hotel policies': 'Políticas del hotel',
    'Rate plan policies': 'Políticas del plan tarifario',
    'Cancellation policies': 'Políticas de cancelación',
    'Warranty policies': 'Políticas de garantia',
    'Credit card policies': 'Políticas de tarjeta de crédito',
    'Night(s)': 'Noche(s)',
    'Reservation number': 'Número de reservación',
    'Confirmation Number' : 'No. Confirmación',
    Source: 'Fuente',
    'Cancellation number': 'Número de cancelación',
    'See reason for cancellation': 'Ver motivo de cancelación',
    'Reason for cancellation': 'Motivo de cancelación',
    Confirmed: 'Confirmado',
    Cancelled: 'Cancelado',
    'In process': 'En proceso',
    Rooms: 'Habitaciones',
    'Room' : 'Habitación',
    Date: 'Fecha',
    'Price per night': 'Precio por noche',
    Occupation: 'Ocupación',
    'Adult(s)': 'Adulto(s)',
    'Extra Adult(s)': 'Adulto(s) Extra',
    Children: 'Niño(s)',
    'Extra Children': 'Niño(s) Extra',
    'Children Age' : 'Edades Niño(s)',
    'The ages are separated by comma (s)' : 'Las edades van separadas por coma(s)',
    'Rate plan': 'Plan tarifario',
    Preferences: 'Preferencias',
    'Waiting to be confirmed': 'En espera por confirmar',
    'Reservation confirmed': 'Reserva confirmada',
    Status: 'Estatus',
    New: 'Nueva',
    Modified: 'Modificada',
    Canceled: 'Cancelada',
    'Cost summary': 'Resumen de costos',
    Taxes: 'Impuestos',
    'Hotel confirmation': 'Confirmación del hotel',
    'Payment details': 'Datos de pago',
    'Reserved by': 'Reservado por',
    Reference: 'Referencia',
    'Pending payment': 'Pago pendiente',
    'Authorization number': 'Número de autorización',
    'Credit card': 'Tarjeta de crédito',
    'View card data': 'Ver datos de tarjeta',
    Send: 'Enviar',
    'Bank deposit': 'Deposito bancario',
    'Online payment': 'Pago en línea',
    'Payment at the hotel': 'Pago en el hotel',
    minute: 'minuto',
    second: 'segundo',
    'The code must be added before': 'El código debe ser agregado antes de',
    'A verification code has been sent to your email, with which you can view the card details': 'Se ha enviado un código de verificación a su correo, con el cual podra visualizar los datos de la tarjeta',
    'Please confirm by email once payment is made to': 'Por favor confirme por email una vez realizado el pago a',
    'Collection dept': 'Depto. cobranza',
    'Invalid verification code': 'Código de verificación incorrecto',
    'There was a problem sending the mail': 'Hubo un problema al enviar el correo',
    'Guest name': 'Nombre dl huésped',
    'Expired session': 'Sesión expirada',
    'The session expires due to inactivity': 'La sesión expiró por inactividad',
    Keep: 'Mantener',
    Options: 'Opciones',
    SendEmail: 'Enviar Correo',
    'Send email with reservation details?': "¿Enviar correo electrónico con detalles de la reserva?",
    'Email Sent': 'Correo Enviado',
    'Email Not Sent': 'Correo no enviado',
    'Commission Zentauro Solutions': 'Comisión Zentauro Solutions',
    'Payment Gateway': 'Pasarela',
    'Total Hotel': 'Total Hotel',
    'Agency': 'Agencia',
    'User': 'Usuario',
    'An Email has been sent to the following users':'Se ha enviado un correo a los siguientes usuarios',
    'Client' : 'Cliente',
    'Hotel':'Hotel',
    'There was an error sending e-mail':'Hubo un error al enviar el correo electrónico',
    'Reactivate':'Reactivar',
    'Reactivate Reservation ?' : '¿ Reactivar Reservación ?',
    'Promotion' : 'Promoción',
    'Cancelled By' : 'Cancelado por',
    'Reason' : 'Motivo',
    'PMS Status' : 'Estatus en PMS',
    'Print' : 'Imprimir',
    'Extra Occupation': 'Ocupacion Extra',
    'Price per night extre person(s)' : 'Precio por noche persona(s) extra',
    'Taxes Hotel' : 'Impuestos Hotel',
    'Total debt' : 'Monto pendiente por pagar',
    'Total deposited' : 'Total depositado',
    'Total Booking' : 'Total Reserva',
    'Confirm Deposit' : 'Confimar Depósito',
    'Confirmation Deposit' : 'Confirmación de depósito',
    'Bank Account' : 'Cuenta Bancaria',
    'Bank' : 'Banco',
    'Amount to Deposit' : 'Monto a Depositar',
    'Details' : 'Detalles',
    'Only numbers' : 'Solo números',
    'Only letters' : 'Solo letras',
    'Only two decimals' : 'Hasta dos decimales',
    'Save' : 'Guardar',
    'Save ?' : '¿ Guardar ?',
    'Save Deposit?' : '¿ Guardar Depósito ?',
    'Deposit has been confirmed' : 'El depósito se ha confirmado',
    'Deposit has not been confirmed' : 'El depósito no se ha confirmado',
    'Ecotax' : 'Ecotasa',
    'Reservation Collected' : 'Reserva Recolectada',
    'Waiting to be collected' : 'Pendiente de Recolectar',
    'Reactivate PMS ?' : '¿ Reactivar PMS ?',
    'Maximun attempts reached' : 'Número de intentos arrebasados',
    'Pms updated' : 'Se ha actualizado el pms',
    'Pms did not update' : 'No se pudo actualizar el pms',
    'Pms has been reactivated' : 'Se ha reactivado pms',
    'Pms has not been reactivated' : 'No se pudo reactivar pms',
    'Change PMS Status' : 'Cambiar Status del PMS',
    'Rates per day summary' : 'Resumen de tarifa por noche',
    'Rates dates can not overlap' : 'Las fechas de tarifas por noche no deben traslaparse',
    'Add New Rate': 'Agregar Nueva Tarifa',
    'Price' : 'Precio',
    'Extra Price' : 'Precio Extra',
    'Price NR' : 'Precio NR',
    'Extra Price NR' : 'Precio Extra NR',
    'Add Rate' : 'Agregar Tarifa',
    'Remove Rate' : 'Remover Tarifa',
    'Reservation dates and rooms rates dates does not match' : 'La fecha de reservación y la fecha de las tarifas de las habitaciones no coinciden',
    'All rooms must has rates' : 'Todas las habitaciones deben de tener tarifas',
    'Until two decimal places' : 'Hasta dos decimales',
    'Send notification email' : 'Enviar correo de notificación',
    'Taxes Included' : 'Incluye Impuestos',
    'Change only status' : 'Cambiar solamente status',
    'Action': 'Operación',
    'Track Record' : 'Historial de Movimientos',
    'Track record' : 'Historial de movimientos',
    'records' : 'movimientos',
    'Close' : 'Cerrar',
    'There are no records that match your request': 'No hay registros que coincidan con su solicitud',
    'Modification Source' : 'Fuente de Modificación',
    'Showing' : 'Mostrando',
    'page' : 'la página',
    'of' : 'de',
    'Cancellation' : 'Cancelación',
    'Modification' : 'Modificación',
    'Reactivation' : 'Reactivación',
    'Deposited to' : 'Depositado a',
    'Send confimation email?' : '¿Enviar correo de confirmación?',
    'Send confimation email' : 'Enviar correo de confirmación',
    'There are no records' : 'No hay movimientos',
    'Bank' : 'Banco',
    'Who Collects' : 'Quien Recolecta',
    'No payment information' : 'No hay información de pago',
    'Call Center Other' : 'Call Center Otro',
    'Information Payment' : 'Información de pago',
    'Check as not verified' : 'Marcar como no verifcada',
    'Verified booking' : 'Verificar Reservación',
    'Verification Code' : 'Código de Verificación',
    'Code' : 'Código',
    'Saved' : 'Guardado',
    'Error' : 'Error',
    'With this action the reservation will be available to be downloaded for the pms' : 'Con esta acción la reserva estara disponible para ser descargada para el pms',
    'Send Again' : 'Enviar de Nuevo',
    'Prices' : 'Precios',
    'Only data that have been updated are displayed' : 'Solo se muestran los datos que han sido actualizados',
    'Virtual Card' : 'Tarjeta Virtual',
    'Amount to be charged' : 'Monto a cobrar'
}