export default {
    'Customer information': 'Información del cliente',
    Name: 'Nombre',
    'Last names': 'Apellidos',
    Phone: 'Teléfono',
    Email: 'Correo electrónico',
    'Card number': 'Número de tarjeta',
    Show: 'Mostrar',
    Type: 'Tipo',
    'Security code': 'Código de seguridad',
    'Expiration date': 'Fecha de expiración',
    Hide: 'Ocultar',
    'Check in': 'Llegada',
    'Check out': 'Salida',
    'Reservation date': 'Fecha de reservación',
    'Client data': 'Datos del cliente',
    'Your reservation was modified': 'Su reserva fue modificada',
    'Your reservation was canceled': 'Su reserva fue cancelada',
    'Your reservation was reactivated': 'Su reserva fue reactivada',
    'Failed to modify the reservation': 'Error al modificar la reserva',
    'Failed to cancel the reservation': 'Error al cancelar la reserva',
    'Failed to reactivate the reservation': 'Error al reactivar la reserva',
    'Modify reservation': 'Modificar reserva',
    Modify: 'Modificar',
    Cancel: 'Cancelar',
    'Are you sure you want to cancel?': '¿Seguro que desea cancelar?',
    'Reason to cancel': 'Motivo para cancelar',
    Exit: 'Salir',
    'Reservation details': 'Detalles de la reservación',
    Policies: 'Políticas',
    'Hotel policies': 'Políticas del hotel',
    'Rate plan policies': 'Políticas del plan tarifario',
    'Cancellation policies': 'Políticas de cancelación',
    'Warranty policies': 'Políticas de garantia',
    'Credit card policies': 'Políticas de tarjeta de crédito',
    'Night(s)': 'Noche(s)',
    'Reservation number': 'Número de reservación',
    Source: 'Fuente',
    'Cancellation number': 'Número de cancelación',
    'See reason for cancellation': 'Ver motivo de cancelación',
    'Reason for cancellation': 'Motivo de cancelación',
    Confirmed: 'Confirmado',
    Cancelled: 'Cancelado',
    'In process': 'En proceso',
    Rooms: 'Habitaciones',
    Date: 'Fecha',
    'Price per night': 'Precio por noche',
    Occupation: 'Ocupación',
    'Adult(s)': 'Adulto(s)',
    Children: 'Niño(s)',
    'Rate plan': 'Plan tarifario',
    Preferences: 'Preferencias',
    'Waiting to be confirmed': 'En espera por confirmar',
    'Reservation confirmed': 'Reserva confirmada',
    Status: 'Estatus',
    New: 'Nueva',
    Modified: 'Modificada',
    Canceled: 'Cancelada',
    'Cost summary': 'Resumen de costos',
    Taxes: 'Impuestos',
    'Hotel confirmation': 'Confirmación del hotel',
    'Payment details': 'Datos de pago',
    'Reserved by': 'Reservado por',
    Reference: 'Referencia',
    'Pending payment': 'Pago pendiente',
    'Authorization number': 'Número de autorización',
    'Credit card': 'Tarjeta de crédito',
    'View card data': 'Ver datos de tarjeta',
    Send: 'Enviar',
    'Bank deposit': 'Deposito bancario',
    'Online payment': 'Pago en línea',
    'Payment at the hotel': 'Pago en el hotel',
    minute: 'minuto',
    second: 'segundo',
    'The code must be added before': 'El código debe ser agregado antes de',
    'A verification code has been sent to your email, with which you can view the card details': 'Se ha enviado un código de verificación a su correo, con el cual podra visualizar los datos de la tarjeta',
    'Please confirm by email once payment is made to': 'Por favor confirme por email una vez realizado el pago a',
    'Collection dept': 'Depto. cobranza',
    'Invalid verification code': 'Código de verificación incorrecto',
    'There was a problem sending the mail': 'Hubo un problema al enviar el correo',
    'Guest name': 'Nombre dl huésped',
    'Expired session': 'Sesión expirada',
    'The session expires due to inactivity': 'La sesión expiró por inactividad',
    Keep: 'Mantener',
    Options: 'Opciones',
    SendEmail: 'Enviar Correo',
    'Send email with reservation details?': "¿Enviar correo electrónico con detalles de la reserva?",
    'Email Sent': 'Correo Enviado',
    'Email Not Sent': 'Correo no enviado',
    'Commission Internet Power': 'Comisión Internet Power',
    'Payment Gateway': 'Pasarela',
    'Total Hotel': 'Total Hotel',
    'Agency': 'Agencia',
    'User': 'Usuario',
    'An Email has been sent to the following users':'Se ha enviado un correo a los siguientes usuarios',
    'Client' : 'Cliente',
    'Hotel':'Hotel',
    'There was an error sending e-mail':'Hubo un error al enviar el correo electrónico',
    'Reactivate':'Reactivar',
    'Reactivate Reservation ?' : '¿ Reactivar Reservación ?',
    'Promotion' : 'Promoción',
    'Cancelled By' : 'Cancelado por',
    'Reason' : 'Motivo',
    'PMS Status' : 'Estatus en PMS',
    'Print' : 'Imprimir',
    'Extra Occupation': 'Ocupacion Extra'
};