export default {
    'Customer information':'Información del cliente',
    Name:'Nombre',
    'Last names':'Apellidos',
    Phone:'Teléfono',
    Email:'Correo electrónico',
    'Card number':'Número de tarjeta',
    Show:'Mostrar',
    Type:'Tipo',
    'Security code':'Código de seguridad',
    'Expiration date':'Fecha de expiración',
    Hide:'Ocultar',
    'Check in':'Llegada',
    'Check out':'Salida',
    'Reservation date':'Fecha de reservación',
    'Client data':'Datos del cliente',
    'Your reservation was modified':'Su reserva fue modificada',
    'Failed to modify the reservation':'Error al modificar la reserva',
    'Modify reservation':'Modificar reserva',
    Modify:'Modificar',
    'Your reservation was canceled':'Su reserva fue cancelada',
    'Failed to cancel the reservation':'Error al cancelar la reserva',
    Cancel:'Cancelar',
    'Are you sure you want to cancel?':'¿Seguro que desea cancelar?',
    'Reason to cancel':'Motivo para cancelar',
    Exit:'Salir',
    'Reservation details':'Detalles de la reservación',
    Policies:'Políticas',
    'Hotel policies':'Políticas del hotel',
    'Rate plan policies': 'Políticas del plan tarifario',
    'Cancellation policies':'Políticas de cancelación',
    'Warranty policies':'Políticas de garantia',
    'Credit card policies':'Políticas de tarjeta de crédito',
    'Night(s)':'Noche(s)',
    'Reservation number':'Número de reservación',
    Source:'Fuente',
    'Cancellation number':'Número de cancelación',
    'See reason for cancellation':'Ver motivo de cancelación',
    'Reason for cancellation':'Motivo de cancelación',
    Confirmed:'Confirmado',
    Cancelled:'Cancelado',
    'In process': 'En proceso',
    Rooms:'Habitaciones',
    Date:'Fecha',
    'Price per night':'Precio por noche',
    Occupation:'Ocupación',
    'Adult(s)':'Adulto(s)',
    Children:'Niño(s)',
    'Rate plan':'Plan tarifario',
    Preferences:'Preferencias',
    'Waiting to be confirmed': 'En espera por confirmar',
    'Reservation confirmed':'Reserva confirmada',
    Status:'Estatus',
    New:'Nueva',
    Modified:'Modificada',
    Canceled:'Cancelada',
    'Cost summary':'Resumen de costos',
    Taxes:'Impuestos',
    'Hotel confirmation':'Confirmación del hotel',
    'Payment details':'Datos de pago',
    'Reserved by':'Reservado por',
    Reference:'Referencia',
    'Pending payment':'Pago pendiente',
    'Authorization number':'Número de autorización',
    'Credit card':'Tarjeta de crédito',
    'View card data':'Ver datos de tarjeta',
    Send:'Enviar',
    'Bank deposit':'Deposito bancario',
    'Online payment':'Pago en línea',
    'Payment at the hotel':'Pago en el hotel',
    minute:'minuto',
    second:'segundo',
    'The code must be added before':'El código debe ser agregado antes de',
    'A verification code has been sent to your email, with which you can view the card details':'Se ha enviado un código de verificación a su correo, con el cual podra visualizar los datos de la tarjeta',
    'Please confirm by email once payment is made to':'Por favor confirme por email una vez realizado el pago a',
    'Collection dept':'Depto. cobranza',
    'Invalid verification code':'Código de verificación incorrecto',
    'There was a problem sending the mail':'Hubo un problema al enviar el correo',
    'Guest name':'Nombre dl huésped',
    'Expired session':'Sesión expirada',
    'The session expires due to inactivity':'La sesión expiró por inactividad',
    Keep:'Mantener',
};
