/* eslint-disable */
export default {
    'Room and Rateplan Closure' : 'Cierre de Habitación y Plan Tarifario',
    'Date Range': 'Rango de Fechas',
    'View Availability' : 'Mostrar Disponibilidad',
    'Load' : 'Cargar',
    'Rate Plans' : 'Planes Tarifarios',
    'Search by rateplan' : 'Buscar por plan tarifario',
    'Status' : 'Status',
    'Open' : 'Abierto',
    'Close' : 'Cerrado',
    'No Arrivals' : 'No Llegadas',
    'O' : 'A',
    'C' : 'C',
    'N' : 'N',
    'Save' : 'Guardar',
    'Dates For Closure' : 'Fechas para Cierre',
    'Rooms' : 'Habitaciones',
    'All' : 'Todos',
    'Show Configurations' : 'Mostrar Configuraciones',
    'Exit' : 'Salir',
    'Couldn\'t Save The Closure' : 'No se pudo guardar el cierre',
    'Add Dates' : 'Agregar Fechas',
    'Dates Overlap' : 'Las fechas se traslapan'  
}