export default {
    'Front2Go Rates Configuration': 'Configuración de Planes Front2Go',
    'Select a corporate': 'Selecciona un corporativo',
    'Search': 'Buscar',
    'F2G New Code': 'Nuevo Código F2G',
    'Save': 'Guardar',
    'elements per page': 'elementos por página',
    'F2G Code': 'Código F2G',
    'Promotion Code': 'Código de promoción',
    'Hotels List': 'Lista de hoteles',
    'Rate Plans List': 'Lista de planes tarifarios',
    'Select': 'Seleccionar',
    'Search Hotels': 'Buscar Hoteles',
    'Search Rate Plans': 'Buscar Planes Tarifarios',
    'Mapped Hotels': 'Hoteles Mapeados',
    'No results found': 'No se han encontrado resultados',
    'The code already exists': 'Ya existe el código',
    'Exit': 'Salir',
    'Hotels with Rate Plan': 'Hoteles con Plan Tarifario',
    'Saved Hotels': 'Hoteles Guardados',
    'Hotels were not saved': 'Los hoteles no se guardaron',
    'Hotels Deleted': 'Hoteles Borrados',
    'Hotels were not deleted': 'Los hoteles no se borraron',
    'Actions': 'Acciones',
    'Rate Plan': 'Plan Tarifario',
    'Hotel Name': 'Nombre Del Hotel',
    'Promotion not valid': 'Promoción no valida'

}