export default {
    'Reservation number': 'No. de reservación',
    Date: 'Fecha',
    Client: 'Cliente',
    Rooms: 'Habitaciones',
    Checkin: 'Salida',
    Checkout: 'Llegada',
    Status: 'Estatus',
    Reserved: 'Reservado',
    Cancelled: 'Cancelado',
    'In process': 'En proceso',
    All: 'Todos',
    'Reservation date': 'Fecha de reservación',
    'Arrival date': 'Fecha llegada',
    'Departure date': 'Fecha salida',
    'Reservation List': 'Listado de Reservaciones',
    'Advanced Search': 'Búsqueda Avanzada',
    'Date Range': 'Rango de Fechas',
    'Search by': 'Buscar por',
    'Room Type': 'Tipo de Habitación',
    'Customer Name': 'Nombre del Cliente',
    Search: 'Buscar',
    Origin: 'Origen',
    Hotels: 'Hoteles',
    'One Page': 'Unipantalla',
    'Front Desk': 'Recepción',
    'Find Hotel': 'Buscar Hotel',
    select: 'seleccionar',
    'It has priority over advanced search': 'Tiene prioridad sobre la búsqueda avanzada',
    'Items per page': 'Elementos por página',
    Download: 'Descargar',
};
