export default {
    'Reservation number': 'No. de reservación',
    'Res. Date': 'Fecha Res.',
    Client: 'Cliente',
    'Guests': 'Huespedes',
    'Comission': 'Comision',
    'Channel': 'Canal',
    'Channels comissions': 'Comision de canales',
    'Save': 'Guardar',
    Rooms: '# Hab.',
    Checkin: 'Llegada',
    Checkout: 'Salida',
    Reserved: 'Reservado',
    Cancelled: 'Cancelado',
    'In process': 'En proceso',
    All: 'Todos',
    'Reservation date': 'Fecha de reservación',
    'Arrival date': 'Fecha llegada',
    'Departure date': 'Fecha salida',
    'Reservation List': 'Listado de Reservaciones',
    'Advanced Search': 'Búsqueda Avanzada',
    'Date Range': 'Rango de Fechas',
    'Search by': 'Buscar por',
    'Room Type': 'Tipo de Habitación',
    'Customer Name': 'Nombre del Cliente',
    'Channel Comissions' : 'Comision de canales',
    Search: 'Buscar',
    Origin: 'Origen',
    Status: 'Estatus',
    Hotels: 'Hoteles',
    'One Page': 'Unipantalla',
    'Front Desk': 'Recepción',
    'Search Hotel': 'Buscar Hotel',
    'Search Corporate': 'Buscar Corporativo',
    select: 'seleccionar',
    'It has priority over advanced search': 'Tiene prioridad sobre la búsqueda avanzada',
    'Items per page': 'Elementos por página',
    'Export page': 'Exportar página',
    'items per page': 'elementos por página',
    'There are no records that match your request': 'No hay registros que coincidan con su solicitud',
    'Exit': 'Salir',
    'Can not export page': 'No se puede exportar la página',
    'Corporate': 'Corporativo',
    'Agency': 'Agencia',
    'Agencies': 'Agencias',
    'Agents':'Agentes',
    'Payment Way' : 'Forma de pago',
    'Deposit' : 'Depósito',
    'Nights' : 'Noches',
    'Rooms' : 'Habitaciones',
    'Commission' : 'Comision',
    'Rate' : 'Tarifa',
    'Tax' : 'Impuesto',
    'Close' : 'Cerrar',
    'Register updated successfully' : 'Registro editado correctamente',
    'Register saved successfully' : 'Registro guardado correctamente',
    'Request error' : 'Error en peticion',
    'Request error' : 'Error en peticion',
    'Comissions-Report' : 'Reporte-Comisiones',
    'Show Configured Comissions' : 'Mostrar comisiones guardadas',
    'There are no commissions set up yet.' : 'No hay comisiones configuradas aún.',
    '' : ''
};