'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3623
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ConventionsMeetings

    '''<summary>
    '''Control lblTitleForm.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTitleForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtDiv1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtDiv1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control txtDiv2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtDiv2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control txtDiv3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtDiv3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control AcountPanel.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents AcountPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control lblFiltro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFiltro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control ddlEstatus.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ddlEstatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control btnLoadStatus.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnLoadStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Control grid.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents grid As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''Control TablaPincipal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TablaPincipal As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lbl_NombreEmpresa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NombreEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNombreEmpresa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNombreEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Noches.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Noches As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNoches.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNoches As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_TipoEvento.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_TipoEvento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoEvento.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoEvento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control TableOtroTipoEvento.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TableOtroTipoEvento As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lbl_Fechas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Fechas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Llegada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Llegada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblLlegada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblLlegada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control aIframeLlegada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aIframeLlegada As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lbl_Salida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Salida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblSalida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSalida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control aIframeSalida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aIframeSalida As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lbl_Flexibilidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Flexibilidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblFlexibilidad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFlexibilidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control TablaOtraFechas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TablaOtraFechas As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lbl_FlexibilidadFechas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_FlexibilidadFechas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_FlexibilidadLlegada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_FlexibilidadLlegada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblFlexibilidadLlegada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFlexibilidadLlegada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control aIframeFlexibilidadLlegada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aIframeFlexibilidadLlegada As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lbl_FlexibilidadSalida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_FlexibilidadSalida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblFlexibilidadSalida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFlexibilidadSalida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control aIframeFlexibilidadSalida.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aIframeFlexibilidadSalida As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lbl_NumeroPersonas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroPersonas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroPersonas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroPersonas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitaciones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitaciones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_HabitacionesSon.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_HabitacionesSon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitacionesSencillas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitacionesSencillas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitacionesSencillas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitacionesSencillas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitacionesDobles.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitacionesDobles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitacionesDobles.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitacionesDobles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitacionesTriples.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitacionesTriples As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitacionesTriples.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitacionesTriples As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitacionesJrSuites.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitacionesJrSuites As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitacionesJrSuites.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitacionesJrSuites As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitacionesMasterSuites.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitacionesMasterSuites As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitacionesMasterSuites.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitacionesMasterSuites As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroHabitacionesSuitePresidente.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroHabitacionesSuitePresidente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroHabitacionesSuitePresidente.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroHabitacionesSuitePresidente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Hoteles.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Hoteles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblHoteles.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblHoteles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Salones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Salones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Salon.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Salon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Salon1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Salon1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Salon2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Salon2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Salon3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Salon3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_TipoMontaje.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_TipoMontaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoMontaje1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoMontaje1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoMontaje2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoMontaje2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoMontaje3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoMontaje3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NumeroSalonPersona.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NumeroSalonPersona As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroSalonPersona1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroSalonPersona1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroSalonPersona2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroSalonPersona2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNumeroSalonPersona3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNumeroSalonPersona3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisual.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualPantalla.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualPantalla As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualPantalla.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualPantalla As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualEquipoSonido.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualEquipoSonido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualEquipoSonido.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualEquipoSonido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualAcetatos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualAcetatos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualAcetatos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualAcetatos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualProyectorTransparencias.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualProyectorTransparencias As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualProyectorTransparencias.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualProyectorTransparencias As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualCanion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualCanion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualCanion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualCanion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualLapTop.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualLapTop As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualLapTop.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualLapTop As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualCopiadora.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualCopiadora As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualCopiadora.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualCopiadora As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AudioVisualOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AudioVisualOtro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAudioVisualOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAudioVisualOtro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Alimentos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Alimentos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AlimentosDesayunos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AlimentosDesayunos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAlimentosDesayunos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAlimentosDesayunos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AlimentosComidas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AlimentosComidas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAlimentosComidas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAlimentosComidas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AlimentosCenas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AlimentosCenas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAlimentosCenas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAlimentosCenas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_AlimentosRequiere.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_AlimentosRequiere As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblAlimentosRequiere.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAlimentosRequiere As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Bebidas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Bebidas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasRefresco.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasRefresco As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasRefresco.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasRefresco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasCervezas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasCervezas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasCervezas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasCervezas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasBotella.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasBotella As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasBotella.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasBotella As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasCopeo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasCopeo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasCopeo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasCopeo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasBarraNacional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasBarraNacional As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasBarraNacional.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasBarraNacional As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasAguasFrutas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasAguasFrutas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasAguasFrutas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasAguasFrutas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasDescorcheBotella.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasDescorcheBotella As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasDescorcheBotella.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasDescorcheBotella As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasBarraImportada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasBarraImportada As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasBarraImportada.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasBarraImportada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasDescorchePersona.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasDescorchePersona As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasDescorchePersona.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasDescorchePersona As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_BebidasEN.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_BebidasEN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasEnComidas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasEnComidas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasEnComidas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasEnComidas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasEnCenas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasEnCenas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasEnCenas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasEnCenas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkBebidasEnOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkBebidasEnOtro As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblBebidasEnOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasEnOtro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblBebidasENOtroCual.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblBebidasENOtroCual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_NochesTema.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NochesTema As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkNochesTemaPalenque.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkNochesTemaPalenque As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblNochesTemaPalenque.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNochesTemaPalenque As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkNochesTemaCasino.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkNochesTemaCasino As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblNochesTemaCasino.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNochesTemaCasino As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkNochesTemaOtras.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkNochesTemaOtras As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblNochesTemaOtras.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNochesTemaOtras As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control TableNochesTemaOtras.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TableNochesTemaOtras As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lbl_NochesTemaOtrasCuales.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NochesTemaOtrasCuales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNochesTemaOtrasCuales.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNochesTemaOtrasCuales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ServiciosExternos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ServiciosExternos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosPeleaGallos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosPeleaGallos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosPeleaGallos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosPeleaGallos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosMariachi.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosMariachi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosMariachi.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosMariachi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosTrio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosTrio As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosTrio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosTrio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosCarpas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosCarpas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosCarpas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosCarpas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosManteleriaEspecial.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosManteleriaEspecial As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosManteleriaEspecial.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosManteleriaEspecial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosCentroMesa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosCentroMesa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosCentroMesa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosCentroMesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosEquipoAudioVisual.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosEquipoAudioVisual As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosEquipoAudioVisual.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosEquipoAudioVisual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosRecorridoPorCiudad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosRecorridoPorCiudad As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosRecorridoPorCiudad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosRecorridoPorCiudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkServiciosExternosOtros.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkServiciosExternosOtros As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblServiciosExternosOtros.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblServiciosExternosOtros As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_EventoPorAgenciaViajes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_EventoPorAgenciaViajes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control rbEventoPorAgenciaViajesSi.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rbEventoPorAgenciaViajesSi As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control lblEventoPorAgenciaViajesSi.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblEventoPorAgenciaViajesSi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control TablaAgenciaViajesSi.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TablaAgenciaViajesSi As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control rbEventoPorAgenciaViajesNo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rbEventoPorAgenciaViajesNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control lblEventoPorAgenciaViajesNo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblEventoPorAgenciaViajesNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_CotizadoEn.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_CotizadoEn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control rbCotizadoEnPaquete.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rbCotizadoEnPaquete As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control lblCotizadoEnPaquete.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCotizadoEnPaquete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control rbCotizadoEnHabitacionesAlimentos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rbCotizadoEnHabitacionesAlimentos As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control lblCotizadoEnHabitacionesAlimentos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCotizadoEnHabitacionesAlimentos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control rbCotizadoEnOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rbCotizadoEnOtro As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control lblCotizadoEnOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCotizadoEnOtro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control TableCotizadoEnOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TableCotizadoEnOtro As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lbl_RequerimiestosEspeciales.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_RequerimiestosEspeciales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblRequerimiestosEspeciales.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblRequerimiestosEspeciales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_Contacto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_Contacto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoNombre.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoNombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoNombre.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoNombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoPuesto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoPuesto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoPuesto.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoPuesto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoEmpresa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoEmpresa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoCiudad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoCiudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoCiudad.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoCiudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoCalle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoCalle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoCalle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoCalle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoColonia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoColonia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoColonia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoColonia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoTelefono.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoTelefono As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoTelefono.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoTelefono As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoCodigoPostal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoCodigoPostal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoCodigoPostal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoCodigoPostal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoFax.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoFax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoFax.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoFax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lbl_ContactoEmail.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_ContactoEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblContactoEmail.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblContactoEmail As Global.System.Web.UI.WebControls.Label
End Class
