'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''RedirectToRates class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class RedirectToRates

    '''<summary>
    '''lnkRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRooms As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblOr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDivTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkFaresCatalogue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFaresCatalogue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkLinkRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLinkRooms As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ModifDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModifDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTitleChangeRates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitleChangeRates As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkFares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFares As Global.System.Web.UI.WebControls.LinkButton
End Class
