export default {
    'Promotions': 'Promociones',
    'Promotion code': 'Código de la promoción',
    'Promotion description': 'Descripción de la promoción',
    'Promotion name': 'Nombre de la promoción',
    'Spanish': 'Español',
    'English': 'Ingles',
    'Restrictions': 'Restricciones',
    'Min. nights': 'Noches mín.',
    'Max. nights': 'Noches máx.',
    'Not cancelable': 'No cancelable',
    'Prior cancellation policy': 'Política de cancelación previa',
    'Detailed cancellation policy': 'Política de cancelación detallada',
    'Cancellation policies': 'Políticas de cancelación',
    'For days': 'Por días',
    'For hours': 'Por horas',
    'Per specific hour': 'Por hora específica',
    'Cancel': 'Cancelar',
    'day{s} before check in': 'día{s} antes del check in',
    'hour{s} before check in': 'hora{s} antes del check in',
    'from check in day': 'de la fecha del check in',
    'Cancel {number} day{s} before check in': 'Cancelar {number} día{s} antes del check in',
    'Cancel {number} hour{s} before check in': 'Cancelar {number} hora{s} antes del check in',
    'Cancel before {number} from check in day': 'Cancelar antes {number} de la fecha del check in',
    'before': 'antes',
    'Min. days': 'Días mín.',
    'Max. days': 'Días máx.',
    'Days in advance': 'Días anticipados',
    'Sale period': 'Periodo de venta',
    'Initial date': 'Fecha inicial',
    'Final date': 'Fecha final',
    'Rooms': 'Habitaciones',
    'Select all': 'Seleccionar todo',
    'Rate plans': 'Planes tarifarios',
    'Start date of the trip': 'Fecha incial del viaje',
    'End date of the trip': 'Fecha final del viaje',
    'Promotion valid for specific day': 'Promoción valida para día especifico',
    'No arrivals': 'No llegadas',
    'Exclude promotion in the following days': 'Excluir promoción en los siguientes días',
    'Promotion type': 'Tipo de la promoción',
    'Save': 'Guardar',
    'Free night': 'Noche gratis',
    'Discount': 'Descuento',
    'Every {number}{prefix} night will be free': 'Cada {number}{prefix} noche será gratis',
    'Only the {number}{prefix} night will be free': 'Solo la {number}{prefix} noche será gratis',
    'will be free': 'será gratis',
    'Every': 'Cada',
    'Only': 'Solo',
    'the': 'la',

    //days
    'SU': 'D',
    'M': 'L',
    'TU': 'M',
    'W': 'M',
    'T': 'J',
    'F': 'V',
    'S': 'S',
};