export default {
    'Promotions': 'Promociones',
    'Promotion code': 'Código de la promoción',
    'Promotion description': 'Descripción de la promoción',
    'Promotion name': 'Nombre de la promoción',
    'Spanish': 'Español',
    'English': 'Ingles',
    'Code': 'Código',
    'Restrictions': 'Restricciones',
    'Comisionable' : 'Comisionable',
    'Min. nights': 'Noches mín.',
    'Max. nights': 'Noches máx.',
    'Not cancelable': 'No cancelable',
    'Prior cancellation policy': 'Política de cancelación previa',
    'Detailed cancellation policy': 'Política de cancelación detallada',
    'Cancellation policies': 'Políticas de cancelación',
    'For days': 'Por días',
    'For hours': 'Por horas',
    'Per specific hour': 'Por hora específica',
    'Cancel': 'Cancelar',
    'day{s} before check in': 'día{s} antes del check in',
    'hour{s} before check in': 'hora{s} antes del check in',
    'from check in day': 'de la fecha del check in',
    'Cancel {number} day{s} before check in': 'Cancelar {number} día{s} antes del check in',
    'Cancel {number} hour{s} before check in': 'Cancelar {number} hora{s} antes del check in',
    'Cancel before {number} from check in day': 'Cancelar antes {number} de la fecha del check in',
    'before': 'antes',
    'Min. days': 'Días mín.',
    'Max. days': 'Días máx.',
    'Days in advance': 'Días anticipados',
    'Sale period': 'Periodo de venta',
    'Initial date': 'Fecha inicial',
    'Final date': 'Fecha final',
    'Rooms': 'Habitaciones',
    'Select all': 'Seleccionar todo',
    'Rate plans': 'Planes tarifarios',
    'Start date of the trip': 'Fecha incial del viaje',
    'End date of the trip': 'Fecha final del viaje',
    'Promotion valid for specific day': 'Promoción valida para día especifico',
    'No arrivals': 'No llegadas',
    'Exclude promotion in the following days': 'Excluir promoción en los siguientes días',
    'Promotion type': 'Tipo de la promoción',
    'Save': 'Guardar',
    'Save Promotion ?' : '¿ Guardar Promoción ?',
    'Promotion Saved' : 'Promoción Guardada',
    'Could Not Save Promotion': 'No se pudo guardar la promoción',
    'Free night': 'Noche gratis',
    'Discount': 'Descuento',
    'Every {number}{prefix} night will be free': 'Cada {number}{prefix} noche será gratis',
    'Only the {number}{prefix} night will be free': 'Solo la {number}{prefix} noche será gratis',
    'will be free': 'será gratis',
    'Every': 'Cada',
    'Only': 'Solo',
    'the': 'la',
    'Remove': 'Eliminar',
    'Specify time': 'Especificar hora',
    'Percentage': 'Porcentaje',
    'Application mode': 'Modo de aplicación',
    'Discount application method': 'Modo de aplicación del descuento',
    'Priority to discount rate': 'Prioridad a descuento en tarifa',
    'Sum discount percentage': 'Suma porcentajes de descuento',
    'Additional discount': 'Descuento adicional',
    'Help': 'Ayuda',
    'The <b>application mode</b> will only affect when there is a discount at the tariff level. Otherwise, the discount percentage set here will be applied.': 'El <b>Modo de aplicación</b> solo afectará cuando haya un descuento a nivel de tarifa. En caso contrario se aplicará el porcetaje de descuento que aquí se configure.',
    'Assuming that in the promotion it was configured with a 40% discount and in the rate it was configured with a 20% discount, it would be as follows:': 'Suponiendo que en la promoción se configuré con un 40% de descuento y en la tarifa se configure con un 20% de descuento, quedaría de la siguiente forma:',
    'Only 20% discount will be applied.': 'Solo se aplicará el 20% de descuento.',
    'A 60% discount will be applied.': 'Se aplicará un 60% de descuento.',
    'First the 40% discount will be applied and the result of that will be applied the 20% discount.': 'Primero se aplicará el 40% de descuento y al resultado de eso se le aplicará el 20% de descuento.',
    'Add discount': 'Agregar descuento',
    'Add free night': 'Agregar noche gratis',
    'Add closure': 'Agregar cierre',
    'Combinable promotion': 'Promoción combinable',
    'Rate plans and rooms': 'Planes tarifarios y habitaciones',
    'must not be empty': 'no debe ser vacío',
    'Wrong form': 'Formulario incorrecto',
    'The value in free or discount night must be greater than 0': 'El valor en noche gratis o descuento debe ser mayor a 0',
    'You must select rate plan(s)': 'Debe seleccionar plan(es) tarifario(s)',
    'You must select room(s)': 'Debe seleccionar habitacion(es)',
    'Select': 'Seleccionar',
    'You must select cancellation policies': 'Debe seleccionar políticas de cancelación',
    'You must select start date of trip': 'Debe seleccionar fecha inicial de viaje',
    'You must select end date of the trip': 'Debe seleccionar fecha final del viaje',
    '' : '',
    //days
    'SU': 'D',
    'M': 'L',
    'TU': 'M',
    'W': 'M',
    'T': 'J',
    'F': 'V',
    'S': 'S',
    'Return to Promotions List' : 'Volver al Listado',
    'Priority to rate' : 'Prioridad en tarifa'
};