/* eslint-disable */
export default {
    'room not selected': 'habitación no seleccionada',
    'rate plan not selected': 'rate plan no seleccionado',
    'promo discount must greater than 0 and less than 100': 'el descuento debe ser mayor a 0 y menor a 100',
    'english promo description not defined': 'falta descripción de promoción en inglés',
    'spanish promo description not defined': 'falta descripción de promoción en español',
    'adult rate must be greater than 0': 'precio de adulto debe ser mayor que 0',
    'children rate is 0': 'precio de niño es 0',
    'junior rate is 0': 'precio de junior es 0',
    'all adult rates must be greater than 0': 'todos los precios de adulto debe ser mayores a 0',
    'some children rates are 0': 'algunos precios de niño son 0',
    'some junior rates are 0': 'algunos precios de junior son 0',
    'exception adult rates must be greater than 0': 'precios excepción de adulto deben ser mayores a 0',
    'some exception children rates are 0': 'algunos precios excepción de niño son 0',
    'some exception junior rates are 0': 'algunos precios excepción de junior son 0',
    'extra adult rate is 0': 'precio de adulto extra es 0',
    'extra child rate is 0': 'precio de niño extra es 0',
    'extra junior rate is 0': 'precio de junior extra es 0',
    'booking window end date must be after start date': 'el fin de la ventana de reserva debe ser después del comienzo',
    'max peole must be greater than 0': 'max de personas debe ser mayor a 0',
    'children number cannot be greater than max peole': 'número de niños no puede ser mayor a max de personas',
    'max adults cannot be greater than max peole': 'max de adultos no puede ser mayor a max de personas',
    'max adults must be greater than 0': 'max de adultos debe ser mayor a 0',
    'min adults cannot be greater than max adults': 'min de adultos no puede ser mayor a max de adultos',
    'min advance booking cannot be greater than max advance booking': 'min días previos no puede ser mayor a max días previos',
    'min nights cannot be greater than max nights': 'min de noches no puede ser mayor a max de noches',
    'invalid request, please contact support': 'solicitud invalida, por favor contacte a soporte',
    'Dates Overlap': 'Las fechas se traslapan'
}
/* eslint-enable */