/* eslint-disable */
export default {
    'Daily rates': 'Tarifas por día',
    'rates': 'tarifas',
    'avail': 'disp',
    '{discount}% Off': '{discount}% de descuento',
    'Rates update': 'Actualización de tarifas',
    'room': 'habitación',
    'occupancy': 'ocupación',
    'rate plan': 'plan tarifario',
    'dates': 'fechas',
    'rules': 'reglas',
    'use default': 'usar default',
    'override': 'sobreescribir',
    'show rates by': 'mostrar tarifas por',
    'adults': 'adultos',
    'children': 'niños',
    'juniors': 'juniors',
    'extra': 'extra',
    'base': 'base',
    'prices': 'precios',
    'price exceptions': 'excepciones de precio',
    'promotion': 'promoción',
    '% off': '% de descuento',
    'promotion description': 'descripción de la promoción',
    'english': 'inglés',
    'spanish': 'español',
    'booking window': 'ventana de reservación',
    'no arrivals': 'no llegadas',
    'advance reservation days': 'días previos para reservar',
    'min': 'min',
    'max': 'max',
    'nights': 'noches',
    'max people': 'max personas',
    'extra people': 'personas extra',
    'max adults': 'max de adultos',
    'min adults': 'min de adultos',
    'room prices': 'precios de habitación',
    'tax not included': 'impuestos no incluidos',
    'tax included': 'impuestos incluidos',
    'save': 'guardar',
    'reset': 'reiniciar',
    'bulk update': 'actualización masiva',
    'M': 'L',
    'T': 'M',
    'W': 'X',
    'R': 'J',
    'F': 'V',
    'S': 'S',
    'U': 'D',
    'are you sure?': '¿estás seguro?',
    'yes, save it!': '¡sí, guardar tarifas!',
    'cancel': 'cancelar',
    'successful update': 'actualización exitosa',
    'the form will be set to its initial state': 'el formulario se establecerá en su estado inicial',
    'yes': 'sí',
    'close': 'cerrar',
    'dates for the rate': 'fechas para la tarifa',
    'Add Dates': 'Agregar Fechas'

};
/* eslint-enable */