'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4963
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ctrlPackage

    '''<summary>
    '''Control lblRatecode.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblRatecode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtRateCode.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtRateCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCodePack.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCodePack As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control lblname.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblDescripcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblDescripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblImagen.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblImagen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control fileImagen.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents fileImagen As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''Control ImagenHabitacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ImagenHabitacion As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control lblStartDate.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtStart.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control lblEndDate.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtEnd.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control lblRule.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblRule As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control ddlRules.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ddlRules As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control lblMaxAdultos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblMaxAdultos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtMaxAd.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtMaxAd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvMaxAdultos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvMaxAdultos As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control lblMaxChildren.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblMaxChildren As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtMaxChild.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtMaxChild As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvMaxChild.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvMaxChild As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control lblNoches.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNoches As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtDaysFree.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtDaysFree As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvNoches.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvNoches As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control aPaqueteRubro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aPaqueteRubro As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lblRateApply.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblRateApply As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkGDS.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkGDS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkPortal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkPortal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkUnipantalla.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkUnipantalla As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkADS.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkADS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control lblAplicaGDS.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblAplicaGDS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkGDSAmadeus.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkGDSAmadeus As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkGDSGalileo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkGDSGalileo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkGDSSabre.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkGDSSabre As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkGDSWorldSpan.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkGDSWorldSpan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control trPortal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents trPortal As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Control lblPortal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblPortal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control RVNochesgratis.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RVNochesgratis As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rvAdultos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvAdultos As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rvalNinios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvalNinios As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cvMaxPeople.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cvMaxPeople As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Control lblSeasons.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSeasons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control dgRooms.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dgRooms As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''Control lblmoney.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblmoney As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chkHabitaciones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkHabitaciones As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''Control ADetails.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ADetails As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lblRoomsNames.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblRoomsNames As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control imgclose.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imgclose As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''Control dvRooms.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dvRooms As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control lblPrice.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtPrecio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPrecio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control ddlTypePrice.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ddlTypePrice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control Rangevalidator1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Rangevalidator1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control RdbPaquete.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RdbPaquete As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control RdbPersona.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RdbPersona As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control RdbOcupacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RdbOcupacion As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Control lblPricingNE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblPricingNE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblPricingExc.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblPricingExc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control chk7.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chk1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chk2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chk3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chk4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chk5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chk6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chk6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control btnAddOccRate.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnAddOccRate As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''Control btnCancelOccRate.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnCancelOccRate As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''Control lblODesde.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblODesde As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtDateFrom.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtDateFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control imgAddDate.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imgAddDate As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control lblOHasta.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblOHasta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtDateTo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtDateTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control imgDeleteDate.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imgDeleteDate As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Control lstDates.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lstDates As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''Control lblDateErrorSign.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblDateErrorSign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblDateError.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblDateError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control txtFechas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFechas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control txtPrices.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPrices As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control txtPricesE.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPricesE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control itxtTipoPrecio.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents itxtTipoPrecio As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
