'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class PhotoRooms

    '''<summary>
    '''lblTypeRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypeRoom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstRoomType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRoomType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonMostrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonMostrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfiles As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''attach1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach1 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach2 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach3 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach4 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach5 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach6 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach7 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach8 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach9 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''attach10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attach10 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''btnAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAttach As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescTips As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dlRoomImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlRoomImages As Global.System.Web.UI.WebControls.DataList
End Class
